Rocky_App/Controllers/CartController.cs
using Braintree;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAccess.Repository;
using Rocky_Models;
using Rocky_Models.ViewModels;
using Rocky_Utility;
using Rocky_Utility.BrainTree;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;


namespace rocky.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IBrainTreeGate _brain;

        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IEmailSender _emailSender;

        [BindProperty]
        public ProductUserVM ProductUserVM { get; set; }
        public CartController(IWebHostEnvironment webHostEnvironment, 
            IEmailSender emailSender, IUnitOfWork unitOfWork, IBrainTreeGate brainTreeGate)
        {
            _brain = brainTreeGate;
            _webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
            if(HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart)!= null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
            {
                shoppingCarts = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }
            List<int> prodInCart = shoppingCarts.Select(p => p.ProductId).ToList();
            IEnumerable<Product> products = _unitOfWork.Products.GetAll(p => prodInCart.Contains(p.Id));

            foreach(var prod in products)
            {
                prod.TempSqFt = shoppingCarts.FirstOrDefault(s => s.ProductId == prod.Id) != null ?
                    shoppingCarts.FirstOrDefault(s => s.ProductId == prod.Id).Sqft : prod.TempSqFt;
            }

            return View(products);
        }

        public IActionResult RemoveItem(int id)
        {
            List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
            {
                shoppingCarts = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
                var item = shoppingCarts.FirstOrDefault(item => item.ProductId == id);
                if (item != null)
                {
                    shoppingCarts.Remove(item);
                }
                HttpContext.Session.Set(WC.SessionCart, shoppingCarts);
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ClearCart()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index","Home");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Product> products)
        {
            List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
            foreach (var prod in products)
            {
                shoppingCarts.Add(new ShoppingCart { ProductId = prod.Id, Sqft = prod.TempSqFt });
            }
            HttpContext.Session.Set(WC.SessionCart, shoppingCarts);
            return RedirectToAction(nameof(Summary));

        }

        public IActionResult Summary()
        {
            ApplicationUser applicationUser;
            if (User.IsInRole(WC.AdminRole))
            {
                if (HttpContext.Session.Get<int>(WC.SessionInquiryId) != 0)
                {
                    //cart has been loaded using an inquiry
                    InquiryHeader inquiryHeader = _unitOfWork.InquiryHeaders.
                        FirstOrDefault(inq => inq.Id == HttpContext.Session.Get<int>(WC.SessionInquiryId));
                    applicationUser = new ApplicationUser()
                    {
                        Email = inquiryHeader.Email,
                        FullName = inquiryHeader.FullName,
                        PhoneNumber = inquiryHeader.PhoneNumber
                    };
                }
                else
                {
                    applicationUser = new ApplicationUser();
                }
                var gateWay = _brain.GetGateWay();
                var clientToken = gateWay.ClientToken.Generate();
                ViewBag.ClientToken = clientToken;
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                //var userId = User.FindFirstValue(ClaimTypes.Name);
                applicationUser = _unitOfWork.applicationUsers.FirstOrDefault(au => au.Id == claim.Value);
            }

            List<ShoppingCart> shoppingCarts = new List<ShoppingCart>();
            if (HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart) != null
                && HttpContext.Session.Get<IEnumerable<ShoppingCart>>(WC.SessionCart).Count() > 0)
            {
                shoppingCarts = HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart);
            }
            List<int> prodInCart = shoppingCarts.Select(p => p.ProductId).ToList();
            IEnumerable<Product> products = _unitOfWork.Products.GetAll(p => prodInCart.Contains(p.Id));
            ProductUserVM = new ProductUserVM()
            {
                ApplicationUser = applicationUser,
                ProductList = products.ToList()
            };
            foreach(var item in shoppingCarts)
            {
                ProductUserVM.ProductList.First(p => p.Id == item.ProductId).TempSqFt = item.Sqft;
            }

            return View(ProductUserVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection collection)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (User.IsInRole(WC.AdminRole))
            {
                //we need to create an order
                //var orderTotal = 0.0;
                //foreach(var prod in ProductUserVM.ProductList)
                //{
                //    orderTotal += prod.Price * prod.TempSqFt;
                //}
                OrderHeader orderHeader = new OrderHeader()
                {
                    CreatedByUserId = claim.Value,
                    //FinalOrderTotal = orderTotal,
                    FinalOrderTotal = ProductUserVM.ProductList.Sum(x => x.TempSqFt * x.Price),
                    City = ProductUserVM.ApplicationUser.City,
                    StreetAddress = ProductUserVM.ApplicationUser.StreetAddress,
                    State = ProductUserVM.ApplicationUser.State,
                    PostalCode = ProductUserVM.ApplicationUser.PostalCode,
                    FullName = ProductUserVM.ApplicationUser.FullName,
                    Email = ProductUserVM.ApplicationUser.Email,
                    PhoneNumber = ProductUserVM.ApplicationUser.PhoneNumber,
                    OrderDate = DateTime.Now,
                    OrderStatus = WC.StatusPending
                };
                _unitOfWork.OrderHeaders.Add(orderHeader);
                _unitOfWork.Complete();

                foreach (var prod in ProductUserVM.ProductList)
                {
                    OrderDetail orderDetail = new OrderDetail()
                    {
                        OrderHeaderId = orderHeader.Id,
                        PricePerSqFt = prod.Price,
                        Sqft = prod.TempSqFt,
                        ProductId = prod.Id
                    };
                    _unitOfWork.OrderDetails.Add(orderDetail);
                }
                _unitOfWork.Complete();

                string nonceFromTheClient = collection["payment_method_nonce"];

                var request = new TransactionRequest
                {
                    Amount = Convert.ToDecimal(orderHeader.FinalOrderTotal),
                    PaymentMethodNonce = nonceFromTheClient,
                    OrderId=orderHeader.Id.ToString(),

                    Options = new TransactionOptionsRequest
                    {
                        SubmitForSettlement = true
                    }
                };

                var gateway = _brain.GetGateWay();
                Result<Transaction> result = gateway.Transaction.Sale(request);
                if(result.Target.ProcessorResponseText == "Approved")
                {
                    orderHeader.TransactionId = result.Target.Id;
                    orderHeader.OrderStatus = WC.StatusApproved;
                }
                else
                {
                    orderHeader.OrderStatus = WC.StatusCanceled;
                }
                _unitOfWork.Complete();
                return RedirectToAction(nameof(InquiryConfirmation), new { id = orderHeader.Id});

            }
            else
            {
                //we need to create an inquiry
                var pathToTemplate = _webHostEnvironment.WebRootPath + Path.DirectorySeparatorChar.ToString()
                    + "Templates" + Path.DirectorySeparatorChar.ToString() + "Inquiry.html";
                var subject = "New Inquiry";
                string HtmlBody = "";
                using (StreamReader sr = System.IO.File.OpenText(pathToTemplate))
                {
                    HtmlBody = sr.ReadToEnd();
                }

Rocky_App/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAccess;
using Rocky_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rocky_Utility;
using Rocky_DataAccess.Repository.IRepository;
using Rocky_DataAccess.Repository;

namespace rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objList = _unitOfWork.Categories.GetAll();
            return View(objList);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Categories.Add(obj);
                _unitOfWork.Complete();
                TempData[WC.Success] = "Category created successfully";
                return RedirectToAction("Index");
            }
            else
                TempData[WC.Error] = "Error while creating category";

            return View(obj);

        }

        //Get - Edit
        public IActionResult Edit(int? Id)
        {
            if(Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.Categories.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            return View(obj);
        }

        //Get - Delete
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.Categories.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            return View(obj);
        }
        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                var category = _unitOfWork.Categories.FirstOrDefault(c => c.Id == obj.Id);
                if(category != null)
                {
                    category = obj;
                }
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            else
                return View(obj);

        }

        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult DeleteConfirmed(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.Categories.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            _unitOfWork.Categories.Remove(obj);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

    }
}

Rocky_App/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAccess.Repository;
using Rocky_Models;
using Rocky_Models.ViewModels;
using Rocky_Utility;
using System.Collections.Generic;


namespace rocky.Controllers
{

    [Authorize(Roles = WC.AdminRole)]
    public class InquiryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public InquiryVM inquiryVM { get; set; }
        public InquiryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            inquiryVM = new InquiryVM()
            {
                InquiryHeader = _unitOfWork.InquiryHeaders.FirstOrDefault(inq => inq.Id == id),
                InquiryDetail = _unitOfWork.InquiryDetails.GetAll(inq => inq.InquiryHeaderId == id, includeProperties:"Product")
            };
            return View(inquiryVM);
        }

        [HttpPost]
        public IActionResult Delete()
        {

            _unitOfWork.InquiryDetails.RemoveRange(_unitOfWork.InquiryDetails.GetAll(
                inqdetail => inqdetail.InquiryHeaderId == inquiryVM.InquiryHeader.Id));
            _unitOfWork.InquiryHeaders.Remove(_unitOfWork.InquiryHeaders.FirstOrDefault(h => h.Id == inquiryVM.InquiryHeader.Id));
            _unitOfWork.Complete();

            
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Details()
        {
            List<ShoppingCart> shoppingCartList = new List<ShoppingCart>();
            inquiryVM.InquiryDetail = _unitOfWork.InquiryDetails.GetAll(det => det.InquiryHeaderId == inquiryVM.InquiryHeader.Id);
            foreach(var detail in inquiryVM.InquiryDetail)
            {
                ShoppingCart shoppingCart = new ShoppingCart()
                {
                    ProductId = detail.ProductId
                };
                shoppingCartList.Add(shoppingCart);
            }
            HttpContext.Session.Clear();
            HttpContext.Session.Set(WC.SessionCart, shoppingCartList);
            HttpContext.Session.Set(WC.SessionInquiryId, inquiryVM.InquiryHeader.Id);
            return RedirectToAction("Index", "Cart");
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json(new { data = _unitOfWork.InquiryHeaders.GetAll() });
        }


        #endregion

    }
}

Rocky_App/Views/Shared/_IndvidualProductCard.cshtml
@model Product
@using Rocky_Utility;


<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ','_')">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:2px solid #ff6a00">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@string.Format("{0:c0}", Model.Price)</span> / sqft</label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@WC.ImagePath@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100 text-dark" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge p-2 border w-100 text-dark" style="background-color:aliceblue">@Model.ApplicationType.Name</span>
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p> @Model.ShortDesc</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
            </div>
        </div>
    </div>
</div>

Rocky_App/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor IHttpContextAccessor
@using Rocky_Utility;
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - rocky</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
        <link href="~/FontAwesome/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
        <link rel="stylesheet" href="~/css/toastr.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/tile.png" width="40%" />
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

                            </li>
                            @if (User.IsInRole(WC.AdminRole))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Content Management
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="ApplicationType" asp-action="Index">Application Type</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/register">Create Admin User</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Inquiry/Order Management
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="Inquiry" asp-action="Index">Inquiry</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                                    </div>
                                </li>

                            }
                            <li>
                                @if (IHttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart) != null)
                                {
                                    <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                        @{
                                            var count = IHttpContextAccessor.HttpContext.Session.Get<List<ShoppingCart>>(WC.SessionCart).Count;
                                        }
                                        <i class="fas fa-shopping-cart"></i> &nbsp; (@count)
                                    </a>
                                }
                                else
                                {
                                    <a href="#" class="nav-link">
                                        <i class="fas fa-shopping-cart"></i> &nbsp;(0)
                                    </a>
                                }
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container mb-4 pb-4">
            <main role="main" class="pb-3">
                <partial name="_Notifications" />
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer bg-dark">
            <div class="container text-white-50">
                &copy; 2021 - Rocky
            </div>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>

        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

        @await RenderSectionAsync("Scripts", required: false)
        <ejs-scripts></ejs-scripts>
    </body>
</html>

Rocky_App/Views/Shared/_Notifications.cshtml
@using Rocky_Utility

@if (TempData[WC.Success] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/toastr.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WC.Success]');
    </script>
}

@if (TempData[WC.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/toastr.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WC.Error]');
    </script>
}