Rocky_App/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAccess;
using Rocky_Models;
using System;
using System.Collections.Generic;
using Rocky_Utility;
using System.Linq;
using System.Threading.Tasks;
using Rocky_DataAccess.Repository.IRepository;
using Rocky_DataAccess.Repository;

namespace rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ApplicationTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList = _unitOfWork.ApplicationTypes.GetAll();
            return View(objList);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }
        //Get-Edit
        public IActionResult Edit(int? Id)
        {

            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.ApplicationTypes.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            return View(obj);
        }

        //Get-Delete
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.ApplicationTypes.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            return View(obj);
        }

        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ApplicationTypes.Add(obj);
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            else
                return View(obj);
        }

        //Post-Edit
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult EditPost(ApplicationType obj)
        {
            if (ModelState.IsValid)
            {
                var applicationType = _unitOfWork.ApplicationTypes.FirstOrDefault(a => a.Id == obj.Id);
                if(applicationType != null)
                {
                    applicationType = obj;
                }
                
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            else
                return View(obj);
        }

        public IActionResult DeleteConfirmed(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.ApplicationTypes.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            _unitOfWork.ApplicationTypes.Remove(obj);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }
    }
}

Rocky_App/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Rocky_DataAccess;
using Rocky_Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Rocky_Utility;
using Rocky_DataAccess.Repository.IRepository;
using Rocky_DataAccess.Repository;

namespace rocky.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class CategoryController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> objList = _unitOfWork.Categories.GetAll();
            return View(objList);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }

        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Category obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Categories.Add(obj);
                _unitOfWork.Complete();
                TempData[WC.Success] = "Category created successfully";
                return RedirectToAction("Index");
            }
            else
                TempData[WC.Error] = "Error while creating category";

            return View(obj);

        }

        //Get - Edit
        public IActionResult Edit(int? Id)
        {
            if(Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.Categories.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            return View(obj);
        }

        //Get - Delete
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.Categories.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            return View(obj);
        }
        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(Category obj)
        {
            if (ModelState.IsValid)
            {
                var category = _unitOfWork.Categories.FirstOrDefault(c => c.Id == obj.Id);
                if(category != null)
                {
                    category = obj;
                }
                _unitOfWork.Complete();
                return RedirectToAction("Index");
            }
            else
                return View(obj);

        }

        //Post
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult DeleteConfirmed(int? Id)
        {
            if (Id == null || Id == 0)
                return NotFound();
            var obj = _unitOfWork.Categories.Find(Id.GetValueOrDefault());
            if (obj == null)
                return NotFound();
            _unitOfWork.Categories.Remove(obj);
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }

    }
}

Rocky_App/Views/ApplicationType/Create.cshtml
@model ApplicationType

<form method="post" asp-action="Create">
    <div class="border p-3 bg-white">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Add Application Type</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>

                    </div>

                </div>

                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-controller="Category" asp-action="index" class="btn btn-success w-100">
                                Back
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky_App/Views/ApplicationType/Delete.cshtml
@model ApplicationType
<form method="post" asp-action="DeleteConfirmed">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">
        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Delete Application Type</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>

                </div>
                
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn w-100 btn-danger" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-controller="ApplicationType" asp-action="index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky_App/Views/ApplicationType/Edit.cshtml
@model ApplicationType
@*<form method="post"  I can remove asp-action="Edit", because We are in the Edit page so asp action is Edit by default*@
<form method="post" asp-action="EditPost">
    <input asp-for="Id" hidden />
    <div class="border p-3 bg-white">
        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Edit Application Type</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-controller="ApplicationType" asp-action="index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

Rocky_App/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>

<div class="container p-3 bg-white">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp;Create a New Application Type
            </a>
            
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="70%">@obj.Name</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No application type exists.</p>
    }

</div>